import { useState } from 'react'
import Head from 'next/head'
import Cookie from 'js-cookie'
import { addDays } from 'date-fns'

import { Footer } from '../components/Footer'
import styles from '../styles/Home.module.css'

export default function Home() {
  const token = Cookie.get('token')
  const [isLogged, setIslogged] = useState(!!token);

  function signIn() {
    Cookie.set('token', 'custom-token-here', {
      expires: addDays(new Date(), 1),
    })
    setIslogged(true)
  }

  function signOut() {
    Cookie.remove('token')
    setIslogged(false)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App | Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Public Page
        </h1>

        <div className={styles.grid}>
          <button type="button" onClick={signIn} disabled={isLogged}>Sign In</button>
          <button type="button" onClick={signOut} style={{background: '#e41934'}} disabled={!isLogged}>Sign Out</button>
        </div>
        <div className={styles.grid}>
          <a href="/private-client" style={{marginRight: '1rem'}}>Private Client</a>
          <a href="/private-ssr" style={{marginLeft: '1rem'}}>Private SSR</a>
        </div>
      </main>

      <Footer />
    </div>
  )
}
